discovery:
  # Key used to group endpoints by clusters
  # meta_cluster_key: "CLUSTER"
  consul_sd_config:
    server: localhost:8500
    tag_separator: ','
    scheme: https
    allow_stale: true
    refresh_interval: 30s
    tags:
    - milvus-proxy
client_config:
  ### AUTH ###
  # Enable authentication
  auth_enabled: true
  # Env variable to use to retrieve the credentials
  username_env: "MILVUS_USERNAME"
  password_env: "MILVUS_PASSWORD"
  ### TLS ###
  # Tag to use in the discovery to determine wether or not the probe should connect to cluster in SSL
  tls_tag: "tls"
  # Address to connect meta key
  address_meta_key: "external_cluster_fqdn"
  ### Probe discovery configuration ###
  ### Probe configuration ###
  monitoring_database: monitoring
  monitoring_collection_latency_rw: monitoring_latency_rw
  monitoring_collection_latency: monitoring_latency_ro
  monitoring_collection_durability: monitoring_durability
  latency_rw_key_prefix: latency_rw_
  latency_init_key_prefix: latency_init_
  durability_key_prefix: durability_
  init_flag_key: init_flag
  init_items_per_collection: 10000
  latency_rw_insert_per_check: 10
  # Timeouts
  load_timeout: 120s
  search_timout: 120s
  initial_flush_timeout: 300s
  index_timeout: 600s
  ensure_database_timeout: 600s
  ### Client connection configuration ###
  max_retry: 3 # Specifies the maximum number of times the client should retry the connection.
  max_backoff: 3s # Specifies the maximum back-off duration for the connection (time.Duration)
checks_configs:
  latency_check:
    enable: true
    interval: 500ms
  durability_check:
    enable: true
    interval: 600s
