discovery:
  # Key used to group endpoints by clusters
  # meta_cluster_key: "CLUSTER"
  consul_sd_config:
    server: localhost:8500
    tag_separator: ','
    scheme: https
    allow_stale: true
    refresh_interval: 30s
    tags:
    - milvus-proxy
client_config:
  ### AUTH ###
  # Enable authentication
  auth_enabled: true
  # Env variable to use to retrieve the credentials
  username_env: "MILVUS_USERNAME"
  password_env: "MILVUS_PASSWORD"
  ### TLS ###
  # Tag to use in the discovery to determine wether or not the probe should connect to cluster in SSL
  tls_tag: "tls"
  # Address to connect meta key
  address_meta_key: "external_cluster_fqdn"
  ### Probe discovery configuration ###
  # The key prefix to discover milvus's databases through service discovery
  database_meta_key_prefix: "milvus-monitoring-"
  ### Probe configuration ###
  monitoring_set: monitoring
  latency_key_prefix: monitoring_latency_
  durability_key_prefix: monitoring_durability_
  durability_key_total: 100 # Number of keys to generate for the durability check
  ### Client connection configuration ###
  max_retry: 3 # Specifies the maximum number of times the client should retry the connection.
  max_backoff: 3s # Specifies the maximum back-off duration for the connection (time.Duration)
checks_configs:
  latency_check:
    enable: true
    interval: 500ms
  durability_check:
    enable: true
    interval: 600s
